language: python
services:
  - postgresql
python:
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - cd pets
  - python manage.py test
env:
  - DJANGO_SETTINGS_MODULE=pets.settings.dev DB_NAME=test DB_USERNAME=test DB_PASSWORD=test DB_IP=127.0.0.1 DB_PORT=5432 DB_ENGINE=django.db.backends.postgresql_psycopg2
before_script:
  - psql -U postgres -c "CREATE USER test WITH CREATEDB PASSWORD 'test';"
